server:
  port: 7000
  
eureka:  instance:    hostname: eureka7000.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com/eureka      